package usecase

import (
	"context"
	"errors"
	"net/http"

	apperrors "github.com/dhegas/saas_gangsta/internal/common/errors"
	"github.com/dhegas/saas_gangsta/internal/config"
	commonauth "github.com/dhegas/saas_gangsta/internal/domains/user/auth"
	authdomain "github.com/dhegas/saas_gangsta/internal/domains/user/auth/domain"
	authrepo "github.com/dhegas/saas_gangsta/internal/domains/user/auth/repository"
	"github.com/dhegas/saas_gangsta/internal/domains/order/domain"
	"github.com/dhegas/saas_gangsta/internal/domains/order/dto"
	"golang.org/x/crypto/bcrypt"
	"gorm.io/gorm"
)

type partnerOrderUsecase struct {
	repo     domain.PartnerOrderRepository
	authRepo authrepo.AuthRepository
	cfg      *config.Config
}

func NewPartnerOrderUsecase(repo domain.PartnerOrderRepository, authRepo authrepo.AuthRepository, cfg *config.Config) domain.PartnerOrderUsecase {
	return &partnerOrderUsecase{
		repo:     repo,
		authRepo: authRepo,
		cfg:      cfg,
	}
}

func (u *partnerOrderUsecase) GetAllOrders(ctx context.Context, tenantID string, filter dto.OrderFilterParams) ([]dto.OrderResponse, error) {
	orders, err := u.repo.FindAll(ctx, tenantID, filter)
	if err != nil {
		return nil, apperrors.New("INTERNAL_ERROR", "Gagal mengambil daftar pesanan", http.StatusInternalServerError, err)
	}

	result := make([]dto.OrderResponse, 0, len(orders))
	for _, o := range orders {
		result = append(result, toOrderResponse(&o))
	}
	return result, nil
}

func (u *partnerOrderUsecase) GetOrderByID(ctx context.Context, tenantID, orderID string) (*dto.OrderResponse, error) {
	order, err := u.repo.FindByID(ctx, tenantID, orderID)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, apperrors.New("NOT_FOUND", "Pesanan tidak ditemukan", http.StatusNotFound, nil)
		}
		return nil, apperrors.New("INTERNAL_ERROR", "Gagal mengambil detail pesanan", http.StatusInternalServerError, err)
	}

	response := toOrderResponse(order)
	return &response, nil
}

func (u *partnerOrderUsecase) CreateOrder(ctx context.Context, tenantID string, req dto.CreateOrderRequest) (*dto.OrderResponse, error) {
	// 1. Validasi / dapatkan meja makan milik tenant jika ada
	var diningTableID *string
	if req.DiningTableName != nil && *req.DiningTableName != "" {
		tableID, err := u.repo.GetTableByName(ctx, tenantID, *req.DiningTableName)
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) || err.Error() == "record not found" {
				return nil, apperrors.New("BAD_REQUEST", "Meja makan dengan nomor "+*req.DiningTableName+" tidak ditemukan", http.StatusBadRequest, nil)
			}
			return nil, apperrors.New("INTERNAL_ERROR", "Gagal memproses meja makan", http.StatusInternalServerError, err)
		}
		diningTableID = &tableID
	} else if req.DiningTablesID != nil && *req.DiningTablesID != "" {
		tableExists, err := u.repo.CheckTableExists(ctx, tenantID, *req.DiningTablesID)
		if err != nil {
			return nil, apperrors.New("INTERNAL_ERROR", "Gagal memvalidasi meja makan", http.StatusInternalServerError, err)
		}
		if !tableExists {
			return nil, apperrors.New("BAD_REQUEST", "Meja makan tidak ditemukan atau bukan milik tenant ini", http.StatusBadRequest, nil)
		}
		diningTableID = req.DiningTablesID
	}

	// 2. Kumpulkan ID menu yang dipesan
	menuIDs := make([]string, 0, len(req.Items))
	for _, item := range req.Items {
		menuIDs = append(menuIDs, item.MenuID)
	}

	// 3. Ambil detail harga dan nama menu dari database untuk validasi & kalkulasi harga aman (tenant-isolated)
	menuDetails, err := u.repo.GetMenuDetails(ctx, tenantID, menuIDs)
	if err != nil {
		return nil, apperrors.New("INTERNAL_ERROR", "Gagal memvalidasi item pesanan", http.StatusInternalServerError, err)
	}

	var totalOrderPrice float64
	var orderItems []domain.OrderItemEntity

	// 4. Bangun order_items dan kalkulasi subtotal menggunakan data valid dari DB
	for _, reqItem := range req.Items {
		detail, exists := menuDetails[reqItem.MenuID]
		if !exists {
			return nil, apperrors.New("BAD_REQUEST", "Salah satu menu yang dipesan tidak valid, tidak tersedia, atau bukan milik tenant ini", http.StatusBadRequest, nil)
		}

		subtotal := float64(reqItem.Quantity) * detail.Price
		totalOrderPrice += subtotal

		orderItems = append(orderItems, domain.OrderItemEntity{
			MenuID:    reqItem.MenuID,
			MenuName:  detail.Name,
			Quantity:  reqItem.Quantity,
			UnitPrice: detail.Price,
			Subtotal:  subtotal,
			Notes:     reqItem.Notes,
		})
	}

	var userID *string
	var autoGeneratedAccessToken string

	// AUTO-REGISTER LOGIC: Jika pembeli mengisi Email dan Password di checkout
	if req.Customer != nil && req.Customer.Email != "" && req.Customer.Password != "" {
		// Cek email apakah sudah terdaftar
		existingUser, err := u.authRepo.FindByEmail(ctx, req.Customer.Email)
		if err != nil {
			return nil, apperrors.New("INTERNAL_ERROR", "Gagal memeriksa status email", http.StatusInternalServerError, err)
		}

		if existingUser != nil {
			return nil, apperrors.New("CONFLICT", "Email sudah terdaftar. Silakan login terlebih dahulu untuk memesan.", http.StatusConflict, nil)
		}

		// Hash password customer baru
		passwordHash, err := bcrypt.GenerateFromPassword([]byte(req.Customer.Password), bcrypt.DefaultCost)
		if err != nil {
			return nil, apperrors.New("INTERNAL_ERROR", "Gagal memproses kata sandi akun", http.StatusInternalServerError, err)
		}

		// Daftarkan customer baru ke tabel users
		newUser := &authdomain.User{
			Email:        req.Customer.Email,
			FullName:     req.Customer.FullName,
			PasswordHash: string(passwordHash),
			Role:         "CUSTOMER",
			IsActive:     true,
		}

		if err := u.authRepo.CreateUser(ctx, newUser); err != nil {
			return nil, apperrors.New("INTERNAL_ERROR", "Gagal mendaftarkan akun baru", http.StatusInternalServerError, err)
		}

		uid := newUser.ID
		userID = &uid

		// Generate JWT Access Token agar otomatis terautentikasi (auto-login)
		accessToken, err := commonauth.GenerateAccessToken(
			newUser.ID,
			newUser.Role,
			"", // Customer global, bebas dari batasan satu tenant
			u.cfg.JWTAccessTokenExpiry,
			u.cfg.JWTSecret,
		)
		if err == nil {
			autoGeneratedAccessToken = accessToken
		}
	} else if req.UserID != nil {
		// Jika order dikirimkan oleh user terautentikasi (Skenario B yang sudah login sebelumnya)
		userID = req.UserID
	}

	var customerName string
	if req.Customer != nil {
		customerName = req.Customer.FullName
	}

	// 5. Bangun entitas Order
	orderEntity := &domain.OrderEntity{
		TenantID:       tenantID,
		UserID:         userID,
		DiningTablesID: diningTableID,
		Status:         "PENDING",
		TotalPrice:     totalOrderPrice,
		CustomerName:   customerName,
	}

	if req.Customer != nil && req.Customer.Email != "" && req.Customer.Password != "" {
		orderEntity.User = &domain.UserEntity{
			ID:       *userID,
			FullName: req.Customer.FullName,
			Email:    req.Customer.Email,
		}
	} else if req.UserID != nil {
		authUser, err := u.authRepo.FindByID(ctx, *req.UserID)
		if err == nil && authUser != nil {
			orderEntity.User = &domain.UserEntity{
				ID:       authUser.ID,
				FullName: authUser.FullName,
				Email:    authUser.Email,
			}
		}
	}

	// 6. Simpan secara transaksional
	if err := u.repo.CreateWithItems(ctx, orderEntity, orderItems); err != nil {
		return nil, apperrors.New("INTERNAL_ERROR", "Gagal menyimpan pesanan", http.StatusInternalServerError, err)
	}

	response := toOrderResponse(orderEntity)
	response.AccessToken = autoGeneratedAccessToken

	return &response, nil
}

func (u *partnerOrderUsecase) UpdateOrderStatus(ctx context.Context, tenantID, orderID string, req dto.UpdateOrderStatusRequest) (*dto.OrderResponse, error) {
	err := u.repo.UpdateStatus(ctx, tenantID, orderID, req.Status)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, apperrors.New("NOT_FOUND", "Pesanan tidak ditemukan", http.StatusNotFound, nil)
		}
		return nil, apperrors.New("INTERNAL_ERROR", "Gagal memperbarui status pesanan", http.StatusInternalServerError, err)
	}

	return u.GetOrderByID(ctx, tenantID, orderID)
}

func (u *partnerOrderUsecase) SoftDeleteOrder(ctx context.Context, tenantID, orderID string) error {
	err := u.repo.SoftDelete(ctx, tenantID, orderID)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return apperrors.New("NOT_FOUND", "Pesanan tidak ditemukan", http.StatusNotFound, nil)
		}
		return apperrors.New("INTERNAL_ERROR", "Gagal menghapus pesanan", http.StatusInternalServerError, err)
	}
	return nil
}

// helper untuk mapping response
func toOrderResponse(entity *domain.OrderEntity) dto.OrderResponse {
	var itemsResp []dto.OrderItemResponse
	if entity.Items != nil {
		for _, item := range entity.Items {
			itemsResp = append(itemsResp, dto.OrderItemResponse{
				ID:        item.ID,
				MenuID:    item.MenuID,
				MenuName:  item.MenuName,
				Quantity:  item.Quantity,
				UnitPrice: item.UnitPrice,
				Subtotal:  item.Subtotal,
				Notes:     item.Notes,
			})
		}
	}

	customerName := entity.CustomerName
	if customerName == "" && entity.User != nil {
		customerName = entity.User.FullName
	}

	return dto.OrderResponse{
		ID:             entity.ID,
		TenantID:       entity.TenantID,
		UserID:         entity.UserID,
		DiningTablesID: entity.DiningTablesID,
		Status:         entity.Status,
		TotalPrice:     entity.TotalPrice,
		CreatedAt:      entity.CreatedAt,
		UpdatedAt:      entity.UpdatedAt,
		Items:          itemsResp,
		CustomerName:   customerName,
	}
}

func (u *partnerOrderUsecase) GetPublicOrderStatus(ctx context.Context, tenantID, orderID string) (*dto.PublicOrderDetailsResponse, error) {
	order, tableName, err := u.repo.GetPublicOrderDetails(ctx, tenantID, orderID)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, apperrors.New("NOT_FOUND", "Pesanan tidak ditemukan", http.StatusNotFound, nil)
		}
		return nil, apperrors.New("INTERNAL_ERROR", "Gagal mengambil status pesanan", http.StatusInternalServerError, err)
	}

	var customerResp dto.PublicCustomerDetails

	itemsResp := make([]dto.PublicOrderItemResponse, 0, len(order.Items))
	for _, item := range order.Items {
		itemsResp = append(itemsResp, dto.PublicOrderItemResponse{
			MenuName: item.MenuName,
			Quantity: item.Quantity,
			Notes:    item.Notes,
			Subtotal: item.Subtotal,
		})
	}

	return &dto.PublicOrderDetailsResponse{
		ID:         order.ID,
		Status:     order.Status,
		TotalPrice: order.TotalPrice,
		CreatedAt:  order.CreatedAt,
		Customer:   customerResp,
		DiningTable: dto.PublicDiningTableDetails{
			TableName: tableName,
		},
		Items: itemsResp,
	}, nil
}

func (u *partnerOrderUsecase) GetPublicOrdersList(ctx context.Context, tenantID string, filter dto.PublicOrderFilterParams) ([]dto.PublicOrderDetailsResponse, error) {
	orders, tableNames, err := u.repo.FindAllPublicOrders(ctx, tenantID, filter)
	if err != nil {
		return nil, apperrors.New("INTERNAL_ERROR", "Gagal mengambil daftar pesanan", http.StatusInternalServerError, err)
	}

	result := make([]dto.PublicOrderDetailsResponse, 0, len(orders))
	for _, o := range orders {
		var customerResp dto.PublicCustomerDetails

		itemsResp := make([]dto.PublicOrderItemResponse, 0, len(o.Items))
		for _, item := range o.Items {
			itemsResp = append(itemsResp, dto.PublicOrderItemResponse{
				MenuName: item.MenuName,
				Quantity: item.Quantity,
				Notes:    item.Notes,
				Subtotal: item.Subtotal,
			})
		}

		var tableName string
		if o.DiningTablesID != nil {
			tableName = tableNames[*o.DiningTablesID]
		}

		result = append(result, dto.PublicOrderDetailsResponse{
			ID:         o.ID,
			Status:     o.Status,
			TotalPrice: o.TotalPrice,
			CreatedAt:  o.CreatedAt,
			Customer:   customerResp,
			DiningTable: dto.PublicDiningTableDetails{
				TableName: tableName,
			},
			Items: itemsResp,
		})
	}

	return result, nil
}


