basePath: /api/v1
definitions:
  dto.CreateSubscriptionPlanRequest:
    properties:
      billingCycle:
        description: 'contoh: monthly, yearly'
        type: string
      description:
        type: string
      isActive:
        type: boolean
      name:
        type: string
      price:
        type: number
    required:
    - billingCycle
    - description
    - name
    - price
    type: object
  dto.UpdateSubscriptionPlanRequest:
    properties:
      billingCycle:
        type: string
      description:
        type: string
      isActive:
        type: boolean
      name:
        type: string
      price:
        type: number
    type: object
  dto.UpdateTenantStatusRequest:
    properties:
      status:
        description: validator.v10 akan memastikan status tidak kosong dan hanya berisi
          nilai tertentu
        enum:
        - active
        - inactive
        - suspended
        type: string
    required:
    - status
    type: object
info:
  contact: {}
  description: Backend API Service untuk platform SaaS POS & Self-Order UMKM kuliner.
  title: saas_gangsta Backend API
  version: "1.0"
paths:
  /admin/dashboard:
    get:
      consumes:
      - application/json
      description: Mengambil overview metrik platform (total tenant, active subscriptions,
        monthly revenue)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get Admin Dashboard Stats
      tags:
      - Admin Dashboard
  /admin/subscriptions/plans:
    get:
      description: 'Mengambil daftar semua paket langganan (misal: Basic, Pro, Enterprise)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get All Subscription Plans
      tags:
      - Admin Subscription
    post:
      consumes:
      - application/json
      description: Membuat paket langganan baru
      parameters:
      - description: Payload Data Paket
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateSubscriptionPlanRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create Subscription Plan
      tags:
      - Admin Subscription
  /admin/subscriptions/plans/{id}:
    patch:
      consumes:
      - application/json
      description: 'Mengubah data paket langganan (termasuk menonaktifkan dengan isActive:
        false)'
      parameters:
      - description: Plan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Data Update
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateSubscriptionPlanRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update Subscription Plan
      tags:
      - Admin Subscription
  /admin/tenants:
    get:
      description: Mengambil daftar seluruh toko/merchant (tenant) yang terdaftar
        di platform
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get All Tenants
      tags:
      - Admin Tenant
  /admin/tenants/{id}/status:
    patch:
      consumes:
      - application/json
      description: Mengubah status operasional tenant (active, inactive, atau suspended)
      parameters:
      - description: Tenant ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Status Baru
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTenantStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update Tenant Status
      tags:
      - Admin Tenant
schemes:
- http
- https
swagger: "2.0"
